Algoritmo "PercentuaisDeVotacao"
// Disciplina  : Introdução à Lógica de Programação e Algoritmos
// Professor   : Luiz Maia
// Descrição   : Escreva um algoritmo para ler o número total de eleitores de um município, o número de votos brancos, nulos e válidos. Calcular e escrever o percentual que cada um representa em relação ao total de eleitores.
// Data atual  : 15/03/2018
Var
// Seção de Declarações das variáveis
 TotalEleitores, TotalVotosNulos, TotalVotosValidos, TotalVotosBrancos : Inteiro
 PercentualVotosNulos, PercentualVotosValidos, PercentualVotosBrancos: Real
Inicio
      Escreva("Indique o total de eleitores do município: ")
      Leia(TotalEleitores)
      Escreva("Indique o total de votos válidos: ")
      Leia(TotalVotosValidos)
      Escreva("Indique o total de votos em branco: ")
      Leia(TotalVotosNulos)
      Escreva("Indique o total de votos nulos: ")
      Leia(TotalVotosBrancos)
      PercentualVotosValidos <- TotalVotosValidos / TotalEleitores * 100
      PercentualVotosNulos <- TotalVotosNulos / TotalEleitores * 100
      PercentualVotosBrancos <- TotalVotosBrancos / TotalEleitores * 100
      Escreval("Votos em branco: ", PercentualVotosBrancos:6:2, "%")
      Escreval("Votos nulos: ", PercentualVotosNulos:6:2, "%")
      Escreval("Votos válidos: ", PercentualVotosValidos:6:2, "%")
Fimalgoritmo
